# Generated by Django 6.0.5 on 2026-06-11 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=500)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
